

set_location_assignment -to PIN_M2 pll_input_clock

set_location_assignment -to PIN_T6 system_control_FPGA_in.system_components_FPGA_in.uart_FPGA_in.uart_rx 
set_location_assignment -to PIN_R6 system_control_FPGA_out.system_components_FPGA_out.uart_FPGA_out.uart_tx
