set_location_assignment $main_clock -to pll_input_clock 

set_location_assignment $uart_rx -to system_control_FPGA_in.system_components_FPGA_in.uart_FPGA_in.uart_transreceiver_FPGA_in.uart_rx_FPGA_in.uart_rx
set_location_assignment $uart_tx -to system_control_FPGA_out.system_components_FPGA_out.uart_FPGA_out.uart_transreceiver_FPGA_out.uart_tx_FPGA_out.uart_tx

set_location_assignment $gate_drive_pwm_0 -to system_control_FPGA_out.system_components_FPGA_out.power_supply_control_FPGA_out.gate_drive_power_FPGA_out.gate_drive_power_pwm_output[0]
set_location_assignment $gate_drive_pwm_1 -to system_control_FPGA_out.system_components_FPGA_out.power_supply_control_FPGA_out.gate_drive_power_FPGA_out.gate_drive_power_pwm_output[1]
set_location_assignment $gate_drive_pwm_2 -to system_control_FPGA_out.system_components_FPGA_out.power_supply_control_FPGA_out.gate_drive_power_FPGA_out.gate_drive_power_pwm_output[2]
set_location_assignment $gate_drive_pwm_3  -to system_control_FPGA_out.system_components_FPGA_out.power_supply_control_FPGA_out.gate_drive_power_FPGA_out.gate_drive_power_pwm_output[3]
set_location_assignment $gate_drive_pwm_4  -to system_control_FPGA_out.system_components_FPGA_out.power_supply_control_FPGA_out.gate_drive_power_FPGA_out.gate_drive_power_pwm_output[4]
set_location_assignment $gate_drive_pwm_5  -to system_control_FPGA_out.system_components_FPGA_out.power_supply_control_FPGA_out.gate_drive_power_FPGA_out.gate_drive_power_pwm_output[5]

set_location_assignment $spi_serial_data -to system_control_FPGA_in.system_components_FPGA_in.spi_sar_adc_FPGA_in.spi_serial_data
set_location_assignment $chip_select -to system_control_FPGA_out.system_components_FPGA_out.spi_sar_adc_FPGA_out.chip_select
set_location_assignment $spi_clock -to system_control_FPGA_out.system_components_FPGA_out.spi_sar_adc_FPGA_out.spi_clock

set_location_assignment $test_ad_mux_0 -to system_control_FPGA_out.system_components_FPGA_out.test_ad_mux[0]	
set_location_assignment $test_ad_mux_1 -to system_control_FPGA_out.system_components_FPGA_out.test_ad_mux[1]	
set_location_assignment $test_ad_mux_2 -to system_control_FPGA_out.system_components_FPGA_out.test_ad_mux[2]	

set_location_assignment $MDIO_inout_data -to system_control_FPGA_inout.system_components_FPGA_inout.ethernet_communication_FPGA_inout.ethernet_FPGA_inout.mdio_driver_FPGA_inout.mdio_three_state_io_driver_FPGA_inout.MDIO_inout_data
set_location_assignment $mdio_clock -to system_control_FPGA_out.system_components_FPGA_out.ethernet_communication_FPGA_out.ethernet_FPGA_out.mdio_driver_FPGA_out.mdio_clock 

set_location_assignment $ethernet_tx_ddr_clock -to ethernet_tx_ddr_io_clock
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to ethernet_tx_ddr_io_clock

set_location_assignment $tx_ctl -to system_control_FPGA_out.system_components_FPGA_out.ethernet_communication_FPGA_out.ethernet_FPGA_out.ethernet_frame_transmitter_FPGA_out.ethernet_tx_ddio_FPGA_out.tx_ctl
set_location_assignment $rgmii_tx_3 -to system_control_FPGA_out.system_components_FPGA_out.ethernet_communication_FPGA_out.ethernet_FPGA_out.ethernet_frame_transmitter_FPGA_out.ethernet_tx_ddio_FPGA_out.rgmii_tx[3]
set_location_assignment $rgmii_tx_2 -to system_control_FPGA_out.system_components_FPGA_out.ethernet_communication_FPGA_out.ethernet_FPGA_out.ethernet_frame_transmitter_FPGA_out.ethernet_tx_ddio_FPGA_out.rgmii_tx[2]
set_location_assignment $rgmii_tx_1 -to system_control_FPGA_out.system_components_FPGA_out.ethernet_communication_FPGA_out.ethernet_FPGA_out.ethernet_frame_transmitter_FPGA_out.ethernet_tx_ddio_FPGA_out.rgmii_tx[1]
set_location_assignment $rgmii_tx_0 -to system_control_FPGA_out.system_components_FPGA_out.ethernet_communication_FPGA_out.ethernet_FPGA_out.ethernet_frame_transmitter_FPGA_out.ethernet_tx_ddio_FPGA_out.rgmii_tx[0]

set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to system_control_FPGA_out.system_components_FPGA_out.ethernet_communication_FPGA_out.ethernet_FPGA_out.ethernet_frame_transmitter_FPGA_out.ethernet_tx_ddio_FPGA_out.tx_ctl
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to system_control_FPGA_out.system_components_FPGA_out.ethernet_communication_FPGA_out.ethernet_FPGA_out.ethernet_frame_transmitter_FPGA_out.ethernet_tx_ddio_FPGA_out.rgmii_tx[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to system_control_FPGA_out.system_components_FPGA_out.ethernet_communication_FPGA_out.ethernet_FPGA_out.ethernet_frame_transmitter_FPGA_out.ethernet_tx_ddio_FPGA_out.rgmii_tx[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to system_control_FPGA_out.system_components_FPGA_out.ethernet_communication_FPGA_out.ethernet_FPGA_out.ethernet_frame_transmitter_FPGA_out.ethernet_tx_ddio_FPGA_out.rgmii_tx[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to system_control_FPGA_out.system_components_FPGA_out.ethernet_communication_FPGA_out.ethernet_FPGA_out.ethernet_frame_transmitter_FPGA_out.ethernet_tx_ddio_FPGA_out.rgmii_tx[0]

   
set_location_assignment $enet_ref_clk_125MHz -to enet_clk_125MHz
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to enet_clk_125MHz

set_location_assignment $rx_ctl -to system_control_FPGA_in.system_components_FPGA_in.ethernet_communication_FPGA_in.ethernet_FPGA_in.ethernet_frame_receiver_FPGA_in.ethernet_rx_ddio_FPGA_in.rx_ctl

set_location_assignment $ethernet_rx_ddio_in_0 -to system_control_FPGA_in.system_components_FPGA_in.ethernet_communication_FPGA_in.ethernet_FPGA_in.ethernet_frame_receiver_FPGA_in.ethernet_rx_ddio_FPGA_in.ethernet_rx_ddio_in[0]
set_location_assignment $ethernet_rx_ddio_in_1 -to system_control_FPGA_in.system_components_FPGA_in.ethernet_communication_FPGA_in.ethernet_FPGA_in.ethernet_frame_receiver_FPGA_in.ethernet_rx_ddio_FPGA_in.ethernet_rx_ddio_in[1]
set_location_assignment $ethernet_rx_ddio_in_2 -to system_control_FPGA_in.system_components_FPGA_in.ethernet_communication_FPGA_in.ethernet_FPGA_in.ethernet_frame_receiver_FPGA_in.ethernet_rx_ddio_FPGA_in.ethernet_rx_ddio_in[2]
set_location_assignment $ethernet_rx_ddio_in_3 -to system_control_FPGA_in.system_components_FPGA_in.ethernet_communication_FPGA_in.ethernet_FPGA_in.ethernet_frame_receiver_FPGA_in.ethernet_rx_ddio_FPGA_in.ethernet_rx_ddio_in[3]
