

set_location_assignment -to PIN_M2 pll_input_clock

set_location_assignment -to PIN_T6 system_control_FPGA_in.system_components_FPGA_in.uart_FPGA_in.uart_rx 
set_location_assignment -to PIN_R6 system_control_FPGA_out.system_components_FPGA_out.uart_FPGA_out.uart_tx

set_location_assignment -to PIN_R13 system_control_FPGA_out.system_components_FPGA_out.power_supply_control_FPGA_out.gate_drive_power_FPGA_out.gate_drive_power_pwm_output[0]
set_location_assignment -to PIN_T12 system_control_FPGA_out.system_components_FPGA_out.power_supply_control_FPGA_out.gate_drive_power_FPGA_out.gate_drive_power_pwm_output[1]
set_location_assignment -to PIN_R12 system_control_FPGA_out.system_components_FPGA_out.power_supply_control_FPGA_out.gate_drive_power_FPGA_out.gate_drive_power_pwm_output[2]
set_location_assignment -to PIN_T5  system_control_FPGA_out.system_components_FPGA_out.power_supply_control_FPGA_out.gate_drive_power_FPGA_out.gate_drive_power_pwm_output[3]
set_location_assignment -to PIN_L1  system_control_FPGA_out.system_components_FPGA_out.power_supply_control_FPGA_out.gate_drive_power_FPGA_out.gate_drive_power_pwm_output[4]
set_location_assignment -to PIN_R4  system_control_FPGA_out.system_components_FPGA_out.power_supply_control_FPGA_out.gate_drive_power_FPGA_out.gate_drive_power_pwm_output[5]

